IF OBJECT_ID('dbo.fn_FormatDate_YYYYMMDD', 'FN') IS NOT NULL
    DROP FUNCTION dbo.fn_FormatDate_YYYYMMDD;
GO

CREATE FUNCTION dbo.fn_FormatDate_YYYYMMDD (@InputDate DATETIME)
RETURNS VARCHAR(8)
AS
BEGIN
    RETURN CONVERT(VARCHAR(8), @InputDate, 112) -- Format: YYYYMMDD
END
GO 
SELECT dbo.fn_FormatDate_YYYYMMDD(GETDATE()) AS FormattedDate;


