IF OBJECT_ID('fn_FormatDate_MMDDYYYY', 'FN') IS NOT NULL
    DROP FUNCTION fn_FormatDate_MMDDYYYY;
GO
CREATE FUNCTION fn_FormatDate_MMDDYYYY (@InputDate DATETIME)
RETURNS VARCHAR(10)
AS
BEGIN
    RETURN CONVERT(VARCHAR(10), @InputDate, 101)  -- MM/DD/YYYY
END
GO
SELECT dbo.fn_FormatDate_MMDDYYYY(GETDATE()) AS FormattedDate;

